### ISSUE TITLE
Dev3 backend deploys seem to be broken

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#4231] opened 2022-09-06 13:53 UTC
### Description
Running the dev3 deploy action seems to fail on the pre-release backend commit deployment step. 

### Steps to reproduce

1. Run the dev3 deploy action
1. Notice the deploy action times out at the staging slot swapping step

https://github.com/CDCgov/prime-simplereport/runs/8208532401?check_suite_focus=true

 ![Screen Shot 2022-09-06 at 9.06.03 AM.png](https://images.zenhubusercontent.com/6196b08a969160bed8994a93/8bfb4719-be62-4f29-a0e0-fb301016ceb8)

### Expected behavior
Deploy action works.

### Additional context
Noticed the error testing a PR to dev3 via the frontend return 502's. Dug further and realized the backend was never deploying.

![Screen Shot 2022-09-06 at 8.29.29 AM.png](https://images.zenhubusercontent.com/6196b08a969160bed8994a93/e8b4ba97-0490-4505-9e31-1727105a34e1)

**Comment by rin-skylight** [comment] 2022-09-12 16:30
Looks like this issue was caused by a database migration that went weird:

```
{"time": "2022-09-12 16:25:29.825", "level": "INFO", "source": "l.lockservice.StandardLockService:42", "message": "Waiting for changelog lock...."}
```

I will advise when the fix is in.

**Comment by rin-skylight** [comment] 2022-09-12 17:11
This appears to be a corrupt migration. The database has been dropped and re-created. Facilities and devices will have to be re-seeded, but the environment is ready for use past that.

**Closed** 2022-09-12 17:19 UTC
Labels: Bug, DevOps, Eng Health
