### ISSUE TITLE
Metrics: Get data to do a funnel analysis on Twilio integrations

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1266] opened 2021-04-08 05:22 UTC
Funnel analysis for the sending results to patient experience:
1. How many links are texted to patients letting them know they have results?
2. How many texts successfully reach patients?
3. How many links are opened by patients?
4. How many patients successfully authenticate with their DOB and view results?

Funnel analysis for the time of test questions patient experience:
1. How many links are texted to patients? For how many test orders?
2. How many texts successfully reach patients?
3. How many links are opened by patients?
4. How many patients successfully authenticate with their DOB?
5. How many click "confirm" on reviewing their information screen?
6. How many patients interact with the time of test questions?
7. How many patients submit their answers to the time of test questions?
8. How many of those submissions contain complete data?
9. How many patients update their data on the "confirm my information" screen with their demographics and contact info?

Side note- can we track successfully texted phone numbers (in other words validated phone numbers) somewhere? I'm guessing this could be useful for us in the future, and also possibly public health departments too.

**Comment by nullflux** [comment] 2021-04-16 16:32
I started on this just a little: https://prime-simple-report-prod-metabase.azurewebsites.net/question/79

We should, moving forward, improve on our ability to track these metrics by adding a table like `messages_sent` with foreign keys to `patient_link` and (the not-yet-merged) `phone_number` as well as a timestamp and the Twilio message sid – but as of this writing, we can glean the top-level metrics we care about from `api_audit_event` and from the fact that test results being sent by SMS results in _exactly two_ patient links existing for a single test order, which is not caused by any other condition at this time

Adding a `messages_sent` table will also allow for us to add a queue worker to ask Twilio for delivery status, and keep track of failed delivery metrics with context for what type of message was sent

**Comment by emmastephenson** [comment] 2021-12-16 17:56
We have a text_status table in the database now

**Closed by emmastephenson** 2021-12-16 17:56 UTC
Labels: Epic, Better Data
