### ISSUE TITLE
Clicking "Submit" tooltip leads to facility selector

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#4484] opened 2022-10-14 00:06 UTC
### Background
Currently, clicking the tooltip next to the `Submit` button on test cards brings you back the facility selector page. Reproduced on `test` and `dev`.

### Expected action
Clicking the tooltip should focus the field, but not trigger a link.

**Comment by emmastephenson** [comment] 2023-01-06 02:53
Duplicate of #4909.

**Closed by emmastephenson** 2023-01-06 02:53 UTC
Labels: Bug, Growth & Engagement
