### ISSUE TITLE
The org admin settings are unreachable in demo 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#894] opened 2021-02-22 15:18 UTC
### Steps to reproduce
- [ ] Navigate to https://demo.simplereport.gov/app/settings
- [ ] Select a facility

### Current results
The user remains on the select facility page

### Expected result
Demo user is able to view the Manage Organization page

https://images.zenhubusercontent.com/302387839/1e841681-7be9-4404-8835-9b850e90c47c/screen_recording_2021_02_22_at_10_19_06_am.mov

**Comment by benwarfield-usds** [comment] 2021-02-23 03:04
This problem appears to have been introduced with the Friday-morning demo front-end deploy. The Friday deploy was of 44eaeb67ef196dc2d4bed759aa21370f5222eb7b; the Thursday deploy was e9e5889e7cacd3f87e27036a1f6d208f6f307bb3. When I went back to try to reproduce this evening's production issue using the previously deployed prod code, I didn't see this problem locally, so there's a fairly narrow range of commits that could have introduced it.

**Comment by benwarfield-usds** [comment] 2021-02-23 03:43
A brief spell of working with `git bisect` while trying to sort out staging/prod issues in another window reveals that the probably-guilty commit is 130b245a880abc8279d5dde14622f083210d413c.

**Comment by nickscialli-usds** [comment] 2021-02-23 16:06
I have a fix for this; encountered it while doing the Settings frontend. The issue is in two parts:

1) We inconsistently append the query string parameters to links in our app. We currently have to remember to do something like `<NavLink to={`some/path/?facility=${activeFacilityId}`}`. We have forgotten to do this in a few places.
2) In the `/settings` subrouter, we `Redirect` any users to the `/settings` route. This strips the facility from the URL. The reason this _seems_ inconsistent is it works fine if there is only one facility in an org as we just default to that. But if there are multiple, our app sees no facility in the search params and can't default to one, so it (a) asks the user for a facility and then promptly (b) redirects the user to `/settings` without a facility in the search params.

The fix for issue 1 is to just create a custom `LinkWithQuery` component that always preserves query parameters.

The fix for issue 2 is to not use a `Redirect` but rather a "default" `Route` in the settings subrouter.

**Closed** 2021-03-01 18:11 UTC
Labels: Bug, Core app, Engineering, Front End
