### ISSUE TITLE
Result called "Inconclusive" in Test Queue but "UNDETERMINED" in Results

### ISSUE THREAD

**Issue by dmethvin-gov** [CDCgov/prime-simplereport#209] opened 2020-12-02 15:16 UTC
I think we should have a map of displayed names to internal database strings for that value.

**Comment by timothybest-usds** [comment] 2021-02-05 16:09
duplicate of https://github.com/CDCgov/prime-simplereport/issues/513

**Closed by timothybest-usds** 2021-02-05 16:09 UTC
Labels: Core app, Engineering, Front End
