### ISSUE TITLE
Add AOE questions to FHIR bundle

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5112] opened 2023-01-24 18:35 UTC
### Description

AOE questions should be added to the FHIR bundle.

### Proposed solution 
Each AOE question needs to be added as an Observation.

### Additional context
This information will be confirmed after talking with the ReportStream team on how this data should be sent to them.

**Comment by mehansen** [comment] 2023-02-14 18:27
Dupe of #5271

**Closed** 2023-02-14 18:27 UTC
Labels: Growth & Engagement, FHIR 🔥
