### ISSUE TITLE
Add SimpleReport intro video to homepage

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2639] opened 2021-09-22 15:20 UTC
Now that the SimpleReport intro video has been approved, we should add it to the homepage of SimpleReport as originally planned.

Need review of the video by PO to make sure we want this to happen, and then discuss prominence on the homepage.

**Comment by emmastephenson** [comment] 2022-02-02 23:51
Duplicate of #3228.

**Closed** 2022-02-02 23:51 UTC
Labels: Design, Growth & Engagement
