### ISSUE TITLE
When a user logs in, prompt them to select which facility they are working at that day

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#404] opened 2020-12-17 18:19 UTC
If an organization has multiple facilities, then when a user logs in they should be prompted to select which facility they are working at that day.

<img width="1311" alt="Screen Shot 2020-12-17 at 1 52 02 PM" src="https://user-images.githubusercontent.com/60664222/102530269-1272e800-406f-11eb-8798-3e44e10f5a57.png">

**Comment by timothybest-usds** [comment] 2020-12-29 18:57
duplicate of https://github.com/CDCgov/prime-simplereport/issues/390

**Closed by timothybest-usds** 2020-12-29 18:57 UTC
Labels: Engineering, Ready for Grooming
