### ISSUE TITLE
Remove `simplereport.gov/resources/**/*` pages from Azure

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1772] opened 2021-06-02 19:03 UTC
We're still seeing old pages like: https://simplereport.gov/resources/using-simplereport/conduct-and-submit-tests/
In addition to the current page: https://simplereport.gov/using-simplereport/conduct-and-submit-tests/

We should remove all `simplereport.gov/resources/**/*` pages from the site bc the old pages are appearing in search results. For example: https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=simplereport&query=%E2%80%9Cfacility+access+request+form%E2%80%9D&commit=

Also, noting that `training.simplereport.gov/*` is appearing in the results

**Comment by benwarfield-usds** [comment] 2021-06-02 19:11
That last thing seems like a thing that robots.txt should take care of—do we have that parameterized by environment?

**Comment by maya** [comment] 2021-06-02 19:15
It's pointed to our sitemap, which I assumed would only show what's there, but we could add an explicit exclude for it

https://github.com/CDCgov/prime-simplereport-site/blob/main/robots.txt

**Comment by maya** [comment] 2021-06-08 18:15
We need a `robots.txt` for the training environment and to disallow it

**Comment by timothybest-usds** [comment] 2021-08-10 18:00
duplicate of https://github.com/CDCgov/prime-simplereport/issues/994

**Closed by timothybest-usds** 2021-08-10 18:00 UTC
Labels: DevOps, Growth & Engagement, P4
