### ISSUE TITLE
Update Test Result value from UNDETERMINED --> Inconclusive

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#306] opened 2020-12-11 22:37 UTC
Test result options in the Test Queue are Positive, Negative, and Inconclusive. In the Results table, they appear as POSITIVE, NEGATIVE, or UNDETERMINED.

For consistency reasons, please: 

- [ ] Update the values from Undetermined --> Inconclusive wherever they occur
- [ ] Use regular capitalization (e.g. "Inconclusive", not "INCONCLUSIVE")

**Comment by timothybest-usds** [comment] 2021-02-05 16:09
duplicate of https://github.com/CDCgov/prime-simplereport/issues/513

**Closed by timothybest-usds** 2021-02-05 16:09 UTC
Labels: Core app, Engineering, Front End
