### ISSUE TITLE
[BUG] Org admin can still edit user after being reassigned to a different organization

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#6505] opened 2023-09-08 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If an org admin has a user on the side nav of the manage user component. The admin is still able to load the user and edit the user's info even after the user has been moved to a different organization.

This happens because getUser operation retrieves the user (now assigned to a different org) as normal.

### Steps To Reproduce

1. As an org admin load the manage user page and pick a user from the sidenav (you don't need to click the name or load the user just make sure you get the email).
2. In another tab, as a site admin, change the user's organization using the email you got in step 1.
3. As an org admin click on the user that just got assigned to other organization and change the name.
4. Verify that the user can be modified even though it does not belong to the org admin's org anymore.

### Expected Behavior

When trying to retrieve the user the operation `getUser` should return an error or not found instead.

### Additional context

@BobanL mentioned that we should add an [okta api call](https://developer.okta.com/docs/reference/api/users/#response-example-36) `clearCurrentUserSession` as part of the operation `updateUserPrivilegeAndAccess` if an org update has been done, as the user also should be asked to re-login and reload the application. This might fix the org admin access issue but that still needs to be confirmed by the developer fixing the bug.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by BobanL** [comment] 2023-09-26 20:32
Testing as an org admin I am not able to reproduce this issue. As an org admin if I try to fetch a user I get an unauthorized error and if I try to update something about the user the site doesn't handle the error and goes to the generic error page.
Although, if I use my site admin account I am able to get and update the user.
Based on what we discussed during standup, we already do [check](https://github.com/CDCgov/prime-simplereport/blob/beaf518dd690fb932ad1ddcf75c458fecf44e6ad/backend/src/main/java/gov/cdc/usds/simplereport/config/authorization/UserAuthorizationVerifier.java#L100) if the current user is in the same org as the one they are trying to edit. This uses the current user's groups from the token and compares it to the target user's groups from okta. 


![Image](https://github.com/CDCgov/prime-simplereport/assets/10108172/657ab34f-b257-4ea0-bd08-f9179208de33)
![Image](https://github.com/CDCgov/prime-simplereport/assets/10108172/968ac06f-beb6-480b-b4c6-db638bb82192)

**Comment by BobanL** [comment] 2023-09-27 20:27
As for trying to clear the session of a user logged in, this does not seem possible with the Okta API since it will only clear [Refresh Token](https://developer.okta.com/docs/reference/api/users/#clear-user-sessions) and not the users current access token. 

In order to fix this, groups would have to be fetched from Okta rather than the token which is already a discussion we had in Eng Sync related to moving groups entirely into our ownership. #6462 is the first step in the process.

**Comment by mehansen** [comment] 2023-10-04 17:18
closing as won't do

**Closed by mehansen** 2023-10-04 17:18 UTC
Labels: Bug, Growth & Engagement, P2
