### ISSUE TITLE
Manage users - Update remove user confirmation modal 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2963] opened 2021-11-15 16:51 UTC
The text should reflect that removing a user will not reset a user's password or MFA. Then, guide them to how to support a user's resets. MFA will require contacting support email, password reset can be done in the manage users area.

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/cd9efa32-0aec-4e2a-9855-342052959669)

**Comment by Rebecca-LM** [comment] 2022-02-08 01:04
@emmastephenson can you provide more context here and what's needed? Is it content or something else?

**Comment by emmastephenson** [comment] 2022-02-08 23:06
Sure thing, the background here is that we often (at least a few times a week) get users in the support inbox who have deleted one of their users and tried to re-add them because the person couldn't sign in. It's usually one of:
- MFA isn't working 
- password is expired or reset and user can't set it again (maybe they forgot security questions)
- user isn't getting account setup email
The problem is that occasionally the user can't be re-added after this deletion has been performed - we have logic to try and make sure re-adding is available, but it's a little buggy and doesn't always work. This also doesn't resolve the user's end problem because removing/re-adding users doesn't change any of their account security settings like MFA or password, so deleting/re-adding won't fix their sign on issues.

The content ask here is to update the model to warn users that deleting people will not change their account security settings in any way, so if you're trying to delete them to "reset" their account it's not going to work.

We do have separate actions for admins to handle all the account reset features (reset MFA, reset password, etc) but users still do this delete/re-add pattern as a last resort if the person still can't log in.

LMK if you have any other questions, happy to hop on a call to explain this flow too!

**Comment by Rebecca-LM** [comment] 2022-02-16 18:25
@fzhao99 copy here

**Remove user**

Are you sure you want to remove **[Last name, First name]**?

Doing so will remove this person's access to SimpleReport. It doesn't reset their account settings or password.

No, go back | Yes, I'm sure

**Comment by fzhao99** [comment] 2022-02-16 18:44
Change super admin link to add devices to ”Add a new testing device”

![image](https://user-images.githubusercontent.com/29645040/154334220-8a7107a2-c63c-4e76-9060-6fdf744fd12d.png)

**Closed** 2022-03-07 13:46 UTC
Labels: Growth & Engagement, Content design
