### ISSUE TITLE
CI on simple-report-site does not catch duplicate ID

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1369] opened 2021-04-20 15:31 UTC
### Description
Two separate `inputs` had the same `id` causing the second input to control the first. This is something that should be caught by our CI system. 

### Expected behavior
If possible configure lighthouse to catch duplicate ids. If not add a Jekyll or HTML linter  that is able to catch this to our github actions

**Comment by maya** [comment] 2021-04-20 16:08
Duplicate of https://github.com/CDCgov/prime-simplereport-site/issues/106

**Closed by maya** 2021-04-20 16:08 UTC
Labels: Bug, Growth & Engagement
