### ISSUE TITLE
Create error message for duplicate organization

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2506] opened 2021-09-08 03:39 UTC
###Problem
There are two issues happening here:

- An admin user abandoned the sign up process and tries to register again.

- A staff member is told they will be using SimpleReport and completes the sign up form.

In both of these cases, users receive an error message with "Duplicate organization" and the are blocked from moving forward. 

###Solution
We want to share an error message that helps users know what to do next, either to help an admin user schedule bookings or a staff member to reach out for access.

**Comment by Rebecca-LM** [comment] 2021-09-10 18:46
@LGFranklin is there a screenshot of the current dup org error they get so I can go from there? I thought I remember working on this previously

**Comment by LGFranklin** [comment] 2021-09-14 04:01
![image](https://user-images.githubusercontent.com/81384847/133193025-87f72ac5-9dbe-4261-9d39-9d6267e6f51d.png)

**Comment by Rebecca-LM** [comment] 2021-09-14 19:40
Got it, thanks! You mentioned adding info either to help an admin user schedule bookings or a staff member to reach out for access, but what is the process to do either?

**Comment by emmastephenson** [comment] 2021-09-20 22:50
Duplicate of #2549

**Closed by emmastephenson** 2021-09-20 22:50 UTC
Labels: Design, Growth & Engagement, Content design
