### ISSUE TITLE
Authentication to Okta should be updated (token or svc acct)

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#4156] opened 2022-08-15 18:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Okta token used in production was generated by someone who no longer is involved in the project (me).  This is mostly okay, but I do have to remember to login to Okta at least every 60 days since if my account becomes locked, the token will not be honored.  This happened once before due to a previous token-owner departing the project.

### Steps To Reproduce

1. lock token owner's account (through inactivity or manually)
2. perform an action that requires okta (login, most admin functions, etc)

### Expected Behavior

The token is owned by a user who is active enough on the project where the 60-day lockout is not an issue.

(or)

A service account is used (ref https://github.com/CDCgov/prime-simplereport/issues/1495).

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment] 2022-08-17 19:21
Thank you for adding this issue @bmaden-usds! Good reminder for us to look at service users again.

**Comment by BobanL** [comment] 2022-08-24 17:25
After doing some investigation on this, I believe we can do the following: 

Create a “service-account” person using [support@simplereport.com](mailto:support@simplereport.com). 
Assign them to a admin role.
Login to account.
Perform MFA via email.
Generate API token from “service-account”
——— 
Create new group - Everyone but service account
Create new [group rule](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-create-group-rules.htm) - example
<img width="398" alt="image" src="https://user-images.githubusercontent.com/10108172/186482038-9f67f59b-f8a1-4dcf-903f-406432cdb7c9.png">
Use the new group in the workflow automation for deactivating accounts
——
Save “service-account” password in vault
Save “service-account” api token in vault

Additional Notes:
- A [service account](https://devforum.okta.com/t/service-account-to-create-api-token/21514) is simply an account not linked to a single individual.
- The token will only be revoke if it (1) Expires, or (2) The issuing user is deactivated. 
- If the password expires, that will not impact the token [note](https://devforum.okta.com/t/do-api-tokens-continue-working-after-the-password-expires/21441)

@rin-skylight, can you please review and make sure it makes sense from a security perspective?

**Comment by emmastephenson** [comment] 2022-08-24 17:43
Thanks for looking into this Boban! Looks like a good plan to me, but I'll defer to Rin on the security side.

@BobanL when you do start setting up the service account, let me know - I'll need to let the Support team know that an account setup email will come in. (I also have access to that inbox but can't grant to others AFAIK)

**Comment by rin-skylight** [comment] 2022-08-25 21:49
@BobanL I have a question about the implementation of this. It's my understanding that the token will expire after a certain period of time due to inactivity. If we have a token that is being used in production now that is subject to a lockout for inactivity, how will switching to a service account benefit us? Will the service account still need manual logins? I would think that if this token was being used in production, it should be auto-renewing each time it's leveraged...there's a gap here that I'm having difficulty filling in.

From a security perspective, my only concern is that giving a service account like this administrative access, and assigning it to an email distribution list, means that our risk of compromise increases by a degree with each person on said list. Do all individuals on the support address have Okta administrative access? If they do not, sending MFA tokens to this address, or providing any sort of password reset capability, may inadvertently grant that access. The more people on a list, the higher the likelihood of a social engineering or phishing attack to be successful, as well.

**Comment by emmastephenson** [comment] 2022-08-25 22:08
@rin-skylight I can confirm that everyone who has access to the support inbox has Okta admin access. I believe that they go through a similar process that we do for overall CDC access before they're granted inbox access.

I can also hopefully shed some light on the token expiration situation. In prod Okta, user accounts are suspended after 60 days if no _human_ activity has been detected (e.g., no login events have occurred for 60 days.) This isn't an Okta default though - we have a workflow automation set up that is essentially a script that runs daily in the middle of the night and suspends any users who meet that 60 day threshold. What Boban is proposing is to create a service account and ensure that it isn't subject to that same workflow automation run, by creating an `Everyone but service user` group that will be referenced by the automation. The service user won't need manual logins (hopefully ever) and you're correct that the API token will auto-refresh every time it's used - that token expiration is separate from the account suspension that Brett is referencing above.

Clear as mud, yes? 😄

**Comment by rin-skylight** [comment] 2022-08-25 23:20
Okay, this all makes a _ton_ more sense. Thank you for the clarifications, @emmastephenson! I learned a few things today.

At this stage, I cannot think of any additional security considerations that would prevent this change from going forward. I'll let you both know if that changes, but I would say "all ahead full" for now!

**Comment by bmaden-usds** [comment] 2022-08-26 11:39
I agree with @rin-skylight 's comment about associating the "service account" with a distribution list.   Seems like there would be a big potential for someone to get the password reset on that account and any other type of MFA that gets enabled for it would have to be shared somehow.

The link @BobanL shared says Okta doesn't support service users.  Since that's the case, I would prefer continuing with a token associated with a single person seems over creating a new user with administrative access that is linked to an email list.

How about just excepting the account used for the token from the 60-day lockout action?

**Comment by BobanL** [comment] 2022-08-26 14:25
Based on my testing, in order to reset a password you need to enter the security question, we will just make the answer to that security question another very secure code and store that in the vault as well. After enough failed attempts the account will be locked (but the api token will still be ok!).
I think it is still preferred to use some generic account though, just in case we ever go through and begin cleaning up users that no longer work on this project. 

@bmaden-usds - Specifically to your point about service accounts -  [Okta's documentation](https://help.okta.com/en-us/Content/Topics/Security/API.htm?cshid=ext_API) says to it's a preferred approach to use service accounts, but it was difficult to find out any documentation on how to actually make them until I found that help thread 😆.

**Comment by emmastephenson** [comment] 2022-09-12 16:10
@BobanL do we need to do anything else to mark this ticket as complete? All the secrets are in Azure and we're using the service account for both prod and nonprod, but I want to double-check before closing.

**Comment by BobanL** [comment] 2022-09-12 17:09
I just checked prod and confirmed that Brett's token hasn't been used since the last time stage & prod was deployed!

**Closed** 2022-09-12 17:09 UTC
Labels: Growth & Engagement, P2
