### ISSUE TITLE
Remove Redux and associated code

### ISSUE THREAD

**Issue by dmethvin-gov** [CDCgov/prime-simplereport#313] opened 2020-12-14 17:08 UTC
Now that we're using graphql there is a lot of Redux-related code that isn't being used. This is particularly a nuisance because a search for names or functionality can mislead you into thinking something is being done when it isn't.

**Comment by timothybest-usds** [comment] 2020-12-15 19:17
duplicate of https://github.com/CDCgov/prime-simplereport/issues/327

**Closed by timothybest-usds** 2020-12-15 19:17 UTC
