### ISSUE TITLE
Queue does not have default sorting

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-simplereport#319] opened 2020-12-14 19:47 UTC
When a patient is added to the queue, the queue refetches the entire queue.

AFAICT, there are no sorting of the patients in the queue on either the front or the backends, so there is no guarantee that the patient would be added to the top of the queue (i think this is the desired location). 

This logic used to exist in the selectors, which are being stripped out. Tracking the regression here

**Comment by dmethvin-gov** [comment] 2020-12-14 21:25
Probably want to close this as a dup of #312, that has some guidance from design on the preferred defaults.

**Comment by benwarfield-usds** [comment] 2020-12-15 05:49
As a front-end matter I would think the patient would be put at the _end_ of the queue immediately (that being how queues normally work), and then you could refetch at your leisure.

**Comment by willusds** [comment] 2020-12-30 20:05
Closed as a dupe of #312

**Closed by willusds** 2020-12-30 20:05 UTC
Labels: Engineering, Front End, Ready for Grooming
