### ISSUE TITLE
[SPIKE] - Eliminate warning and error logs in the frontend

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#6403] opened 2023-08-22 21:31 UTC
### Background
When running the frontend test suite, the output is cluttered with many warnings and errors that make it difficult to debug and understand failed tests. This ticket explores the process for fixing this errors.

### Action requested
Eliminate all the warnings in our frontend tests, starting with the `act` warnings that Johanna has begun to clean up in [these](https://github.com/CDCgov/prime-simplereport/pull/5950) [PR's](https://github.com/CDCgov/prime-simplereport/pull/5950). 

### Acceptance Criteria
Frontend tests are run without warnings. Bonus points if we can determine what the root cause of the warnings are.

### Additional context
[Relevant discussion here](https://github.com/CDCgov/prime-simplereport/pull/5931#discussion_r1218495800)

**Comment by mehansen** [comment] 2023-09-21 16:47
@fzhao99 would you say this is a dupe of #6491?

**Comment by fzhao99** [comment] 2023-09-21 16:55
Yep we can close this one now that that one exists!

**Closed** 2023-09-21 16:55 UTC
Labels: Growth & Engagement, Tech Debt
