### ISSUE TITLE
Remove multiplexEnabled feature flag

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#4301] opened 2022-09-20 20:14 UTC
### Background
The multiplex feature flag was added to limit the functionality per environment.

### Action requested
Now that multiplex has been released, all references to the multiplex feature flag should be removed.

### Acceptance Criteria
All references to the `multiplexEnabled` flag have been removed from the frontend.

**Comment by jayna-SkylightDigital** [comment] 2022-10-14 20:07
Reviewed during backlog grooming on 10/6 and determined that this issue is still needed.

**Comment by mehansen** [comment] 2023-09-27 18:27
dupe of #6348

**Closed by mehansen** 2023-09-27 18:27 UTC
Labels: Joint Backlog
