### ISSUE TITLE
Spike on Adding health alert to function apps

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2808] opened 2021-10-18 20:33 UTC
### Description
Look into add alters for the function apps when it fails to execute. 

### Proposed solution 

Adding health alerts to the following functions

- `QueueBatchedReportStreamUploader`
- `ReportStreamExceptionHandler`

### Additional context
Perhaps triggered by more than one successive failure.

**Comment by emmastephenson** [comment] 2022-02-02 22:26
Dupe of #3319

**Closed by emmastephenson** 2022-02-02 22:26 UTC
Labels: Better Data, postmortem, Eng Health
