### ISSUE TITLE
DOB on the results table is not 508 compliant

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1224] opened 2021-04-01 13:30 UTC
The gray used does not pass color contrast requirements. Please update to use #71767A — the color used in the design!

[Screen Shot 2021-04-01 at 9.29.08 AM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/34fe7a61-c153-49e9-b87e-0b7a3c3c2c23)
![Screen Shot 2021-04-01 at 9.29.46 AM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/36fd7bb9-2b98-41a0-9d93-e70877818cf4)![Screen Shot 2021-04-01 at 9.30.02 AM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/69544ede-d733-4702-80fe-1514a0ad4f91)

**Comment by nickscialli-usds** [comment] 2021-04-01 13:47
@hmyers-cms This is my fault, being fixed quickly in #1225

**Comment by maya** [comment] 2021-04-01 19:17
Fixed in #1225.

@nickscialli-usds FYI we tend to use the convention "Fixes #1225" or "Resolves #1225" in PRs so that when the PR is merged, the issue is auto-closed. Saves us from manually have to close issues.

**Closed by maya** 2021-04-01 19:17 UTC
Labels: Bug, Front End, Growth & Engagement
