### ISSUE TITLE
P4: Backdate Feature firefox support

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#432] opened 2020-12-28 17:01 UTC
- the backdate doesn't work well on firefox. We likely need to strip the `datetime-local` into separate date and time fields. See comment below. This is a lower priority bug imo.

![Screen Shot 2021-01-21 at 9.42.36 AM.png](https://images.zenhubusercontent.com/5fff5452b437d92c58ef1bdb/44f6dc0a-6b28-473d-a4c9-26aaa1cb306a)

**Comment by sharmaneil** [comment] 2021-01-22 18:24
Pending work:
- the `datetime-local` field for the test date (in the test queue) breaks in firefox. Probably needs to be split into ![Screen Shot 2021-01-21 at 9.42.36 AM.png](https://images.zenhubusercontent.com/5fff5452b437d92c58ef1bdb/44f6dc0a-6b28-473d-a4c9-26aaa1cb306a)

**Comment by timothybest-usds** [comment] 2021-02-02 19:41
style issues capture in https://github.com/CDCgov/prime-simplereport/issues/682

**Comment by timothybest-usds** [comment] 2021-02-12 22:21
> Truss’s [React USWDS Date picker component](https://github.com/trussworks/react-uswds/pull/803) PR was merged today into their USWDS React library. But it uses React 17 while we’re on 16
-- Maya

**Comment by timothybest-usds** [comment] 2021-02-12 22:22
Duplicate of https://github.com/CDCgov/prime-simplereport/issues/651

**Comment by timothybest-usds** [comment] 2021-03-02 00:04
Note this might also effect the patient DOB field https://github.com/CDCgov/prime-simplereport/pull/981/commits/d7a03bd6409a1d778cd85ca931940b9e02a505e2

**Comment by timothybest-usds** [comment] 2021-07-19 20:00
wont fix. Firefox is an unsupported browser

**Closed by timothybest-usds** 2021-07-19 20:00 UTC
Labels: Bug, Front end, Growth & Engagement
